/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtonGroup: typeof import('./src/components/Services/ActionButtonGroup.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    CustomSpinner: typeof import('./src/components/CustomSpinner.vue')['default']
    EllaNavbar: typeof import('./src/components/nav/EllaNavbar.vue')['default']
    Form: typeof import('./src/components/Services/Form.vue')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    IBiX: typeof import('~icons/bi/x')['default']
    Media: typeof import('./src/components/Services/Media.vue')['default']
    Page: typeof import('./src/components/Services/Page.vue')['default']
    PlaylistPlayer: typeof import('./src/components/AV-Components/PlaylistPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/nav/Sidebar.vue')['default']
    SidebarService: typeof import('./src/components/nav/SidebarService.vue')['default']
    SingleFileAudioPlayer: typeof import('./src/components/AV-Components/SingleFileAudioPlayer.vue')['default']
    VideoPlayer: typeof import('./src/components/AV-Components/VideoPlayer.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}
