// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { ReadRootGetData, ReadEllaRootEllaIdGetData, ReadEllaRootEllaIdGetResponse, ReadEllaRootEllaIdGetError, ReadEllaServiceEllaIdEllaServiceGetData, ReadEllaServiceEllaIdEllaServiceGetResponse, ReadEllaServiceEllaIdEllaServiceGetError, GetPdfEllaIdEllaServicePdfPostData, GetPdfEllaIdEllaServicePdfPostResponse, GetPdfEllaIdEllaServicePdfPostError, GetMailEllaIdEllaServiceMailPostData, GetMailEllaIdEllaServiceMailPostResponse, GetMailEllaIdEllaServiceMailPostError, GetPrintEllaIdEllaServiceDocprinterDocidGetData, GetPrintEllaIdEllaServiceDocprinterDocidGetError, GetLinkEllaIdEllaServiceLinkPostData, GetLinkEllaIdEllaServiceLinkPostResponse, GetLinkEllaIdEllaServiceLinkPostError, GetDataEllaIdContactSendPostData, GetDataEllaIdContactSendPostResponse, GetDataEllaIdContactSendPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Root
 * 'Ella, elle l'a' (France Gall) Die OpenApi für Deine ella_app ist online.
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Read Ella Root
 * Liefert die Welcome-Page Deiner ella_app zurück. Das folgende Beispiel kannst Du
 * ausprobieren:
 * - ella_id = ella_example_simple
 */
export const readEllaRootEllaIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadEllaRootEllaIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadEllaRootEllaIdGetResponse, ReadEllaRootEllaIdGetError, ThrowOnError>({
        url: '/{ella_id}',
        ...options
    });
};

/**
 * Read Ella Service
 * Liefert den gewünschten Service für Deine ella_app zurück. Folgende Beispiele kannst Du
 * ausprobieren:
 * - ella_id = ella_example_simple
 * - ella_service:
 * - ella_simple_page
 * - ella_simple_service
 * - ella_simple_group
 */
export const readEllaServiceEllaIdEllaServiceGet = <ThrowOnError extends boolean = false>(options: Options<ReadEllaServiceEllaIdEllaServiceGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReadEllaServiceEllaIdEllaServiceGetResponse, ReadEllaServiceEllaIdEllaServiceGetError, ThrowOnError>({
        url: '/{ella_id}/{ella_service}',
        ...options
    });
};

/**
 * Get Pdf
 * Die ella Applikation sendet die Daten passend zu einer Servicebeschreibung. Es wird ein
 * PDF-Dokument zurückgesendet.
 */
export const getPdfEllaIdEllaServicePdfPost = <ThrowOnError extends boolean = false>(options: Options<GetPdfEllaIdEllaServicePdfPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetPdfEllaIdEllaServicePdfPostResponse, GetPdfEllaIdEllaServicePdfPostError, ThrowOnError>({
        url: '/{ella_id}/{ella_service}/pdf',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Mail
 * Die ella Applikation sendet die Daten passend zu einer Servicebeschreibung.
 *
 */
export const getMailEllaIdEllaServiceMailPost = <ThrowOnError extends boolean = false>(options: Options<GetMailEllaIdEllaServiceMailPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetMailEllaIdEllaServiceMailPostResponse, GetMailEllaIdEllaServiceMailPostError, ThrowOnError>({
        url: '/{ella_id}/{ella_service}/mail',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Print
 * Die ella Applikation sendet die Daten passend zu einer Servicebeschreibung.
 *
 */
export const getPrintEllaIdEllaServiceDocprinterDocidGet = <ThrowOnError extends boolean = false>(options: Options<GetPrintEllaIdEllaServiceDocprinterDocidGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, GetPrintEllaIdEllaServiceDocprinterDocidGetError, ThrowOnError>({
        url: '/{ella_id}/{ella_service}/docprinter/{docid}',
        ...options
    });
};

/**
 * Get Link
 * Die ella Applikation sendet die Daten passend zu einer Servicebeschreibung.
 *
 */
export const getLinkEllaIdEllaServiceLinkPost = <ThrowOnError extends boolean = false>(options: Options<GetLinkEllaIdEllaServiceLinkPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetLinkEllaIdEllaServiceLinkPostResponse, GetLinkEllaIdEllaServiceLinkPostError, ThrowOnError>({
        url: '/{ella_id}/{ella_service}/link',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Data
 * Die ella Applikation sendet die Daten passend zum EllaContact Formular. Die Daten werden
 * angenommen und weitergeleitet.
 */
export const getDataEllaIdContactSendPost = <ThrowOnError extends boolean = false>(options: Options<GetDataEllaIdContactSendPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetDataEllaIdContactSendPostResponse, GetDataEllaIdContactSendPostError, ThrowOnError>({
        url: '/{ella_id}/contact/send',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};