// This file is auto-generated by @hey-api/openapi-ts

/**
 * Antwort an die ella_app nach Versand der Kontakt-Nachricht.
 * - "success" Bool-Werte true oder false
 * - "message" Exception-Message bei False, Success-Message bei  true
 */
export type ContactResponse = {
    success: boolean;
    message: string;
};

/**
 * Beispiel eines Kontakt-Formulars einer ella_app.
 */
export type EllaContact = {
    name: string;
    vorname: string;
    subject: string;
    message: string;
    email: string;
    telefon?: string;
    mobil?: string;
};

/**
 * Übergabe von Daten von der **ella_app** an ella
 * ===============================================
 * - "form" = JSON-Datensatz, entspricht dem JSON-Schema des **ella_service**
 * - "additional" = Zusätzliche Daten für den Service im Backend (z.B. E-Mail-Adresse)
 */
export type FormData = {
    form: {
        [key: string]: unknown;
    };
    additional?: {
        [key: string]: unknown;
    };
};

/**
 * Beschreibung eines Formulars
 * ============================
 *
 * Funktionen im ella ecosystem
 * ----------------------------
 * - Aufruf eines **ella_service** durch die **ella_app**:
 * - Die Formularbeschreibung wird als {JSON-Schema} zurückgeliefert. Mit der
 * Formularbeschreibung kann die **ella_app** das Formular anzeigen (engl. rendern).
 * - Aufruf einer **ella_method** durch die **ella_app**:
 * - Die Daten werden von der **ella_app** im {JSON-Format} passend zur
 * Formularbeschreibung übergeben. Die eingehenden Daten werden mittels {JSON-Schema}
 * validiert.
 *
 * Bechreibung der Attribute
 * -------------------------
 * - "name" = ID des Formulars
 * - "title" = Titel des Formulars
 * - "description" = Kurzbeschreibung des Formulars
 * - "type" = 'object'
 * - "properties" = Python-Dictionary zur Beschreibung der Formularfelder
 * - "required" = Liste mit Pflichtfeldern des Formualars
 */
export type FormDescription = {
    name: string;
    title: string;
    description: string;
    type: string;
    properties: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    required: Array<string>;
};

/**
 * Beschreibung eines Services (ella_service) innerhalb einer Service-Gruppe
 * -------------------------------------------------------------------------
 * - "title" = Titel des Service oder der Gruppe
 * - "description" = Kurzbeschreibung des Service oder der Gruppe
 * - "type" = Das Attribut type hat folgende Optionen:
 * * "page" = Es wird eine Seite angezeigt. Der Richtext der Seite steht im Attribut "text"
 * * "service" = Es wird ein Formular angezeigt. Das JSON-Schema des Formulars steht im Attribut "form"
 * - "text" = optional (bei type=page): <HTML> Richtext der Seite
 * - "form" = optional (bei type=form): JSON-Schema der Form
 * - "ui" = optional (bei type=form): UI-Schema der Form
 * - "formactions" = optional: Liste mit Form Actions (Buttons)
 */
export type GroupServiceDescription = {
    name: string;
    title: string;
    description: string;
    type: string;
    text?: string;
    form?: FormDescription;
    media?: MediaContainer;
    ui?: UiSchema;
    formactions?: Array<ServiceButton>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 *
 */
export type MediaContainer = {
    name: string;
    title: string;
    description?: string;
    type: string;
    textbefore?: string;
    textafter?: string;
    mediafiles?: Array<MediaFile>;
};

/**
 *
 */
export type MediaFile = {
    name: string;
    title: string;
    description?: string;
    url: string;
    mimetype: string;
    transcript?: string;
    imageurl?: string;
    imagecaption?: string;
};

/**
 * Rückgabe von Daten vom ELLA-Backend an die PWA
 * - "type" = file, link, oder email
 * - "content" = Inhalt der Datenrückgabe, Beispiele:
 * - File (base64 codiert)
 * - Link (auch mailto:...)
 * - Text
 *
 * - "encoding" = Kondierung des Inhalts von content, Beispiele:
 * - base64
 * - utf-8
 *
 * - "filename" = bei type=file, Name der Datei
 * - "mimeType" = bei type=file, Mimetype des Inhalts von content
 */
export type ResponseData = {
    type: string;
    content: string;
    encoding: string;
    fileName?: string;
    mimeType?: string;
};

/**
 * Beschreibung eines Buttons für den ella_service
 * -----------------------------------------------
 * - "name" = Name oder ID des Buttons = Name des Services der aufgerufen wird
 * - "title" = Beschriftung des Buttons
 * - "cssclass" = Farbe und Aussehen des Buttons
 * - "method" = HTTP-Methode zum Aufruf des Service [GET, POST, PUT, REDIRECT]
 * * HTTP-Methods GET, POST, PUT
 * * REDIRECT-Method für "innerPWA" Aufrufe von Services über den Namen
 * - "modaltitle" = Titel des Modals mit Zusatzinformationen beim Aufruf des Buttons
 * - "modaltext" = Text im Modal vor den Formularfeldern
 * - "additional" = Zusätzliches Modal-Feld mit Daten für den Serviceaufruf z.B. E-Mail-Adresse
 */
export type ServiceButton = {
    name: string;
    title: string;
    cssclass: string;
    method: string;
    modaltitle?: string;
    modaltext?: string;
    additional?: {
        [key: string]: unknown;
    };
};

/**
 * Beschreibung eines Services (ella_service) für die ella_app
 * -----------------------------------------------------------
 * - "title" = Titel des Service oder der Gruppe
 * - "description" = Kurzbeschreibung des Service oder der Gruppe
 * - "type" = Das Attribut type hat folgende Optionen:
 * * "page" = Es wird eine Seite angezeigt. Der Richtext der Seite steht im Attribut "text"
 * * "service" = Es wird ein Formular angezeigt. Das JSON-Schema des Formulars steht im Attribut "form"
 * * "group" = Es handelt sich um eine Gruppe von Services. Die Services stehen dann in "services"
 * * "media" = Es handelt sich um einen Media-Container
 * - "hidden" = optionale Angabe ob der Service im Menü ausgeblendet werden soll. Default: False
 * - "text" = optional (bei type=page): <HTML> Richtext der Seite
 * - "form" = optional (bei type=form): JSON-Schema der Form
 * - "ui" = optional (bei type=form): UI-Schema der Form
 * - "services" = optional (bei type=group): Liste mit weiteren Servicebeschreibungen
 * - "formactions" = optional: Liste mit Form Actions (Buttons)
 */
export type ServiceDescription = {
    name: string;
    title: string;
    description: string;
    type: string;
    hidden?: boolean;
    text?: string;
    form?: FormDescription;
    ui?: UiSchema;
    services?: Array<GroupServiceDescription>;
    media?: MediaContainer;
    formactions?: Array<ServiceButton>;
};

/**
 * UI-Schema für den **ella_service**
 */
export type UiSchema = {
    type: string;
    elements: Array<{
        [key: string]: unknown;
    }>;
};

export type ValidationError = {
    loc: Array<string>;
    msg: string;
    type: string;
};

/**
 * Beschreibung einer Welcome-Page für die ella_app
 * ------------------------------------------------
 *
 * - "title" = Titel der **ella_app**
 * - "description = Kurzbeschreibung der **ella_app**
 * - "bodytext" = <HTML> RichText mit den Inhalten der Welcome-Page
 * - "services" = Listen mit den Servicebeschreibungen der **ella_services** (class: ServiceDescription)
 * - "formactions" = optional: Liste mit Form Actions (Buttons)
 */
export type Welcome = {
    name: string;
    title: string;
    description: string;
    bodytext: string;
    services?: Array<ServiceDescription>;
    formactions?: Array<ServiceButton>;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadEllaRootEllaIdGetData = {
    body?: never;
    path: {
        ella_id: string;
    };
    query?: never;
    url: '/{ella_id}';
};

export type ReadEllaRootEllaIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEllaRootEllaIdGetError = ReadEllaRootEllaIdGetErrors[keyof ReadEllaRootEllaIdGetErrors];

export type ReadEllaRootEllaIdGetResponses = {
    /**
     * Successful Response
     */
    200: Welcome;
};

export type ReadEllaRootEllaIdGetResponse = ReadEllaRootEllaIdGetResponses[keyof ReadEllaRootEllaIdGetResponses];

export type ReadEllaServiceEllaIdEllaServiceGetData = {
    body?: never;
    path: {
        ella_id: string;
        ella_service: string;
    };
    query?: never;
    url: '/{ella_id}/{ella_service}';
};

export type ReadEllaServiceEllaIdEllaServiceGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadEllaServiceEllaIdEllaServiceGetError = ReadEllaServiceEllaIdEllaServiceGetErrors[keyof ReadEllaServiceEllaIdEllaServiceGetErrors];

export type ReadEllaServiceEllaIdEllaServiceGetResponses = {
    /**
     * Successful Response
     */
    200: ServiceDescription;
};

export type ReadEllaServiceEllaIdEllaServiceGetResponse = ReadEllaServiceEllaIdEllaServiceGetResponses[keyof ReadEllaServiceEllaIdEllaServiceGetResponses];

export type GetPdfEllaIdEllaServicePdfPostData = {
    body: FormData;
    path: {
        ella_id: string;
        ella_service: string;
    };
    query?: never;
    url: '/{ella_id}/{ella_service}/pdf';
};

export type GetPdfEllaIdEllaServicePdfPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPdfEllaIdEllaServicePdfPostError = GetPdfEllaIdEllaServicePdfPostErrors[keyof GetPdfEllaIdEllaServicePdfPostErrors];

export type GetPdfEllaIdEllaServicePdfPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseData;
};

export type GetPdfEllaIdEllaServicePdfPostResponse = GetPdfEllaIdEllaServicePdfPostResponses[keyof GetPdfEllaIdEllaServicePdfPostResponses];

export type GetMailEllaIdEllaServiceMailPostData = {
    body: FormData;
    path: {
        ella_id: string;
        ella_service: string;
    };
    query?: never;
    url: '/{ella_id}/{ella_service}/mail';
};

export type GetMailEllaIdEllaServiceMailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMailEllaIdEllaServiceMailPostError = GetMailEllaIdEllaServiceMailPostErrors[keyof GetMailEllaIdEllaServiceMailPostErrors];

export type GetMailEllaIdEllaServiceMailPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseData;
};

export type GetMailEllaIdEllaServiceMailPostResponse = GetMailEllaIdEllaServiceMailPostResponses[keyof GetMailEllaIdEllaServiceMailPostResponses];

export type GetPrintEllaIdEllaServiceDocprinterDocidGetData = {
    body?: never;
    path: {
        ella_id: string;
        ella_service: string;
        docid: string;
    };
    query?: never;
    url: '/{ella_id}/{ella_service}/docprinter/{docid}';
};

export type GetPrintEllaIdEllaServiceDocprinterDocidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPrintEllaIdEllaServiceDocprinterDocidGetError = GetPrintEllaIdEllaServiceDocprinterDocidGetErrors[keyof GetPrintEllaIdEllaServiceDocprinterDocidGetErrors];

export type GetPrintEllaIdEllaServiceDocprinterDocidGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLinkEllaIdEllaServiceLinkPostData = {
    body: FormData;
    path: {
        ella_id: string;
        ella_service: string;
    };
    query?: never;
    url: '/{ella_id}/{ella_service}/link';
};

export type GetLinkEllaIdEllaServiceLinkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLinkEllaIdEllaServiceLinkPostError = GetLinkEllaIdEllaServiceLinkPostErrors[keyof GetLinkEllaIdEllaServiceLinkPostErrors];

export type GetLinkEllaIdEllaServiceLinkPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseData;
};

export type GetLinkEllaIdEllaServiceLinkPostResponse = GetLinkEllaIdEllaServiceLinkPostResponses[keyof GetLinkEllaIdEllaServiceLinkPostResponses];

export type GetDataEllaIdContactSendPostData = {
    body: EllaContact;
    path: {
        ella_id: string;
    };
    query?: never;
    url: '/{ella_id}/contact/send';
};

export type GetDataEllaIdContactSendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDataEllaIdContactSendPostError = GetDataEllaIdContactSendPostErrors[keyof GetDataEllaIdContactSendPostErrors];

export type GetDataEllaIdContactSendPostResponses = {
    /**
     * Successful Response
     */
    200: ContactResponse;
};

export type GetDataEllaIdContactSendPostResponse = GetDataEllaIdContactSendPostResponses[keyof GetDataEllaIdContactSendPostResponses];

export type ClientOptions = {
    baseURL: 'https://ella.uv-kooperation.de' | (string & {});
};